### ISSUE TITLE
Missing search icon when using build.

### ISSUE THREAD

**Issue by arulagrawal** [PrettyCoffee/fluidity#12]
I can't see the ddg/google/qwant icon when I use `npm run build`.

I cloned the repo, changed homepage to "./" in package.json. 

ran `npm i`. 

ran `npm run start` <- the icon is showing at this stage

ran `npm run build`

opened `./build/index.html` in browser -> no icon

Am I missing something?

**Comment by PrettyCoffee** [comment]
Hi, sorry for the late response.
Do you still need help with something?
