### ISSUE TITLE
How to change the icon and name of the tab?

### ISSUE THREAD

**Issue by Zabooby** [PrettyCoffee/fluidity#17]
I am using github pages to host the start page, how to I change the settings so a new tab says new tab and not fluidity.
Also how do I get a custom icon to show on the tab?

**Comment by PrettyCoffee** [comment]
You do use the gh-pages branch to host it, right?

Then you can change the tab title by replacing `<title>Fluidity</title>` with `<title>New tab</title>` (or whatever name you want) inside the `index.html` file.
For the icon, you can just replace the `favicon.ico` file with your icon. You only have to make sure to actually use an `.ico` file. You can use an online converter like [convertio.co](https://convertio.co/png-ico/) to convert other pictures to the `.ico` format.

**Comment by Zabooby** [comment]
Yeah I do, everything else is working perfectly. 

So once I make those changes do I upload it to my forked branch on github?

**Comment by PrettyCoffee** [comment]
Exactly, you just change it inside the gh-pages branch, then push it and wait a few seconds. Then it should be applied to your page :)

**Comment by Zabooby** [comment]
Ok thanks for the help, I'll close the issue once I change everything.

Keep up the good work, your startpage is great!
