### ISSUE TITLE
Is it possible to transfer settings/themes between computers?

### ISSUE THREAD

**Issue by fstripes** [PrettyCoffee/fluidity#19]

**Comment by PrettyCoffee** [comment]
Hello, currently thats not possible in the startpage itself.
However, you can do that manually. The steps may vary based on which browser you are using;

1. Open fluidity
2. Press F12
3. Click the "Storage" tab ("Application" for chrome)
4. Open "Local Storage" on the left hand side and click the now visible entry below
5. Now you should see a table with 4 rows on the right: "design", "link-groups", "search-settings" and "themes"
6. Copy the values from the right column into a text file and copy the textfile onto the other pc
7. Do the same on the other PC but now paste the values into the right column (might have to hit apply changes in the settings of the startpage first if the rows do not appear)

![image](https://user-images.githubusercontent.com/66521452/187520641-163b3cfc-7756-424d-ab45-7fe58b527ccb.png)

I hope this works for you :)

**Comment by fstripes** [comment]
This worked great - thank you!
