### ISSUE TITLE
How to change default settings?

### ISSUE THREAD

**Issue by Zabooby** [PrettyCoffee/fluidity#20]
I have forked fluidity and am using github pages to use it. I was wondering how to change default settings like bookmarks, search engines, fast forward search and themes so when I want to use my fork I don't have to customise it all the time.

**Comment by PrettyCoffee** [comment]
The default data can be found in [src/data/data.ts](https://github.com/PrettyCoffee/fluidity/blob/main/src/data/data.ts).

You can change it to your needs and then use the ["Advanced: Changing the code"](https://github.com/PrettyCoffee/fluidity#advanced-changing-the-code) guide for the workflow on how to test and release the changes on your github-pages branch.

**Comment by Zabooby** [comment]
Thanks for the answer!
