### ISSUE TITLE
How would I change the 'always stay clean' message on the search bar?

### ISSUE THREAD

**Issue by fstripes** [PrettyCoffee/fluidity#22]

**Comment by PrettyCoffee** [comment]
There is no setting for it in the UI.

If you have a fork and want to change it in your copy, you can change it in this file:

https://github.com/PrettyCoffee/fluidity/blob/0fbc90c23da2c811b6e60035ec62ae20a7052ce0/src/Startpage/Searchbar/Searchbar.tsx#L81

Just adapt the `placeholder` prop to what you want. :)

**Comment by PrettyCoffee** [comment]
I will close this due to inactivity. If you still need something, feel free to create a fresh issue :)
