### ISSUE TITLE
Chrome extension

### ISSUE THREAD

**Issue by Hellothere123890** [PrettyCoffee/fluidity#24]
I have tried to turn this into a chrome extension however every attempt has failed. I tried using ChatGPT for help and guidance on how to modify the code so that it would work, but nothing did. The best I can get it a blank screen. If you could could help provide steps on how to turn it into an extension that would be awesome. And yes I am a bit of a noob on these things.

**Comment by PrettyCoffee** [comment]
Hey :)
Did you use the files from the https://github.com/PrettyCoffee/fluidity/tree/gh-pages branch?

And are there any errors in the browsers console?

**Comment by Hellothere123890** [comment]
Yes I did. I just did a fresh download of the branch and tried again. The first error I get is: 
Required value 'version' is missing or invalid. It must be between 1-4 dot-separated integers each between 0 and 65536.
Could not load manifest. 

Since then I have been hosting it locally and now I have a different question. I saw on a different Issues page on how to change the "Always stay clean!" by forking it but from there how do I branch it to make my own gh-pages. I am a bit of a noob when it comes to GitHub and coding stuff.

**Comment by PrettyCoffee** [comment]
Hmm, can you send me your manifest file?
My guess would be that you are either missing the `manifest_version` or `version` field, or that one of the values is invalid (based off the error)

Regarding the text in the search field, you can probably search (ctrl+f) in the `static/js/main.6c628930.js` file for "Always stay clean!" and replace it with what you want it to be. But its important that you keep the `"` symbols where they are and only replace the text.

![image](https://github.com/PrettyCoffee/fluidity/assets/66521452/60d81ea2-a728-4838-a7f3-aa99ce3b79a2)

That should be the easiest solution, if you are not familiar with github.

**Comment by Hellothere123890** [comment]
I was a able to change the place holder. This is awesome!
