### ISSUE TITLE
Add Automated Docker Image Building

### ISSUE THREAD

**Issue by igotQweston** [PrettyCoffee/fluidity#27]
Add automated docker image building for forks of the project using the `Publish Docker Container` in GitHub Actions

The Default configuration works with no additional tweaking

Tested on my own fork of the project: [igotQweston/fluidity](https://github.com/igotQweston/fluidity)

**Comment by PrettyCoffee** [comment]
Hey, first off: Thank you for your interest in improving Fluidity! :)

That being said, I am currently not looking into hosting a docker image of this Project. Everyone that is interested in using fluidity with docker can clone the repo and use the provided Dockerfile.
