### ISSUE TITLE
Non-http protocol wont work

### ISSUE THREAD

**Issue by coddra** [PrettyCoffee/fluidity#31]
I use qutebrowser and when I add e.g. 'qute://settings/' to fluidity it won't open on click.

**Comment by PrettyCoffee** [comment]
Can you provide more details?

When using this in a chromium browser, I get
> Failed to launch 'qute://settings/' because the scheme does not have a registered handler.

Do you have any console output in your browser?

My guess is that `qute://` is just not supported by the `<a>` tag, meaning there is probably nothing I can do about it.

**Comment by coddra** [comment]
Yeah, you're probably right. Sorry, I could've done a bit more research on this.

I created a dull html file:
```html
<a href="qute://settings/">Settings</a>
```

Well... Qutebrowser won't open settings on clicking the link.
