### ISSUE TITLE
Webpage appears blank after forking

### ISSUE THREAD

**Issue by Epexity** [PrettyCoffee/fluidity#32]
Hello, so after forking the project and setting up the page via Github Pages, the page itself appears blank and nothing loads. The source code itself can be seen via inspect. It appears that the repo is broken after forking. I'm getting this console error: 

> "Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.".

I already tried to changing the index and vite config, but nothing helps. Is there a way to fix it? I would really appreciate an answer, since I really like how this startpage looks but I just want a tiny bit more of customization

**Comment by PrettyCoffee** [comment]
Hey, it seems like you are using the `main` branch for github-pages. However, you must use the [`gh-pages`](https://github.com/Epexity/fluidity/tree/gh-pages) branch. Then it should work :)

Explanation:
The main branch uses code / features that can not be used natively by the browser (e.g. dependencies, syntax extensions). For the browser to be able to show the startpage, the code must first be:
- *transpiled*: Convert syntax extensions (such as typescript and jsx) to javascript 
- and *bundled*: All files and external packages (such as the react library) are combined  into a few bigger files

This is what you can find inside the `gh-pages` branch: The result of the process described above.

**Comment by PrettyCoffee** [comment]
As an addition, these are the github pages settings in my repo:
![image](https://github.com/user-attachments/assets/91f11f12-a13d-451f-a9af-7190e10090df)

**Comment by Epexity** [comment]
Thank you, that worked! I didn't know it would be that easy. Actually tried switching to the gh-pages branch, but nothing changed, but I just deleted and forked the repo again and now it works.
